spring:
  main:
    banner-mode: off
  datasource:
    username: postgres
    password: fpt@123456
    url: jdbc:postgresql://localhost:4001/techstore-api-db
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
  redis:
    client-name: master
    password: fpt@123456
    url: redis://localhost:4002
  servlet:
    multipart:
      enabled: true
      max-file-size: 500000KB
      max-request-size: 500000KB
cloudinary:
  cloud-name: fpt-software-quiz
  api-key: 446252591291621
  api-secret: w6AQxknBfDg_ykT_NKFlTOOxQsw
