package com.techstore.ecommerce.object.constant;

public enum Authorities {

    // PRODUCT
    PRODUCT_READ("PRODUCT_READ"),
    PRODUCT_CREATE("PRODUCT_CREATE"),
    PRODUCT_UPDATE("PRODUCT_UPDATE"),
    PRODUCT_DELETE("PRODUCT_DELETE"),

    // USER
    USER_READ("USER_READ"),
    USER_CREATE("USER_CREATE"),
    USER_UPDATE("USER_UPDATE"),
    USER_DELETE("USER_DELETE"),

    // ROLE
    ROLE_READ("ROLE_READ"),
    ROLE_CREATE("ROLE_CREATE"),
    ROLE_UPDATE("ROLE_UPDATE"),
    ROLE_DELETE("ROLE_DELETE"),

    // CUSTOMER
    CUSTOMER_READ("CUSTOMER_READ"),
    CUSTOMER_CREATE("CUSTOMER_CREATE"),
    CUSTOMER_UPDATE("CUSTOMER_UPDATE"),
    CUSTOMER_DELETE("CUSTOMER_DELETE"),

    // BRAND
    BRAND_READ("BRAND_READ"),
    BRAND_CREATE("BRAND_CREATE"),
    BRAND_UPDATE("BRAND_UPDATE"),
    BRAND_DELETE("BRAND_DELETE"),

    // CATEGORY
    CATEGORY_READ("CATEGORY_READ"),
    CATEGORY_CREATE("CATEGORY_CREATE"),
    CATEGORY_UPDATE("CATEGORY_UPDATE"),
    CATEGORY_DELETE("CATEGORY_DELETE"),

    // ORDER
    ORDER_READ("ORDER_READ"),
    ORDER_CREATE("ORDER_CREATE"),
    ORDER_UPDATE("ORDER_UPDATE"),
    ORDER_DELETE("ORDER_DELETE"),

    // RECEIPT
    RECEIPT_READ("RECEIPT_READ"),
    RECEIPT_CREATE("RECEIPT_CREATE"),
    RECEIPT_UPDATE("RECEIPT_UPDATE"),
    RECEIPT_DELETE("RECEIPT_DELETE"),

    // SUPPLIER
    SUPPLIER_READ("SUPPLIER_READ"),
    SUPPLIER_CREATE("SUPPLIER_CREATE"),
    SUPPLIER_UPDATE("SUPPLIER_UPDATE"),
    SUPPLIER_DELETE("SUPPLIER_DELETE");

    private final String permission;

    public String getPermission() {
        return permission;
    }

    Authorities(String permission) {
        this.permission = permission;
    }
}
